/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2darraysassignment;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author 348848128
 */
public class drawingPanel extends javax.swing.JPanel {

    /**
     * Creates new form drawingPanel
     */
    
    CGame game = new CGame();
    int boxHeight = 10;
    int boxWidth = 10;
    int rows=800/10;
    int cols=600/10;
    
    
    public drawingPanel() {
        initComponents();
        game.initializeGrid(rows,cols);
        
    }
    
    
    
    boolean update = true;
    
    int cellRed=255;
    int cellGreen=255;
    int cellBlue=255;
    
    int backRed=0;
    int backGreen=0;
    int backBlue=0;
  
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        if(update){
        game.grid = game.updateGrid(rows,cols);
        
        }
        
        for(int y=0;y<game.grid.length;y++){
            for(int x=0;x<game.grid[0].length;x++){
                if(game.grid[y][x]==true){
                    g.setColor(new Color(cellRed,cellGreen,cellBlue));
                    g.fillRect(x *boxWidth,y * boxHeight , (x * boxWidth) + boxWidth ,(y * boxHeight) + boxHeight);
                   
                    
                }else if(game.grid[y][x]==false){
                    g.setColor(new Color(backRed,backGreen,backBlue));
                     g.fillRect(x *boxWidth,y * boxHeight , (x * boxWidth) + boxWidth ,(y * boxHeight) + boxHeight);
                }
            }
        }
        
        
    }
    
    Timer t1;

    public void timer() {
        t1 = new Timer(100, new TimerListener());
    }

    private class TimerListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            drawingPanel.super.repaint();

        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
